plank:
  default_decoration_configs:
    '*':
      timeout: 1h
      grace_period: 15s
      utility_images: # using the tag we identified above
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20200520-e1124f454"
        initupload: "gcr.io/k8s-prow/initupload:v20200520-e1124f454"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20200520-e1124f454"
        sidecar: "gcr.io/k8s-prow/sidecar:v20200520-e1124f454"
      gcs_configuration:
        bucket: bells17-labs
        path_strategy: explicit
      gcs_credentials_secret: gcs-credentials # the secret we just made
      ssh_key_secrets:
        - ssh-secret
  job_url_prefix_config:
    '*': https://prow.bells17.io/view/gcs/

sinker:
  resync_period: 1m
  max_prowjob_age: 48h
  max_pod_age: 48h
  terminated_pod_ttl: 30m

prowjob_namespace: default
pod_namespace: test-pods
log_level: debug

tide:
  sync_period: 2m
  queries:
  - orgs:
    - bells17-labs
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/blocked-paths
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - needs-rebase
  context_options:
    orgs:
      bells17-labs:
        skip-unknown-contexts: false
        from-branch-protection: true
  blocker_label: tide/merge-blocker
  squash_label: tide/merge-method-squash
  rebase_label: tide/merge-method-rebase
  merge_label: tide/merge-method-merge
  pr_status_base_urls:
    '*': https://prow.bells17.io/pr

github_reporter:
  job_types_to_report:
  - presubmit
  - postsubmit

# slack_reporter_configs:
#   '*':
#     job_types_to_report:
#       - presubmit
#       - postsubmit
#       - periodic
#       - batch
#     job_states_to_report:
#       - failure
#       - error
#     channel: prow-error
#     # The template shown below is the default
#     report_template: 'Job {{.Spec.Job}} of type {{.Spec.Type}} ended with state {{.Status.State}}. <{{.Status.URL}}|View logs>'

deck:
  spyglass:
    size_limit: 500000000  # 500 MB
    gcs_browser_prefix: https://console.cloud.google.com/storage/browser/
    # testgrid_config: gs://k8s-testgrid/config
    # testgrid_root: https://testgrid.k8s.io/
    announcement: "Welcome to spyglass!"
    lenses:
    - lens:
        name: metadata
      required_files:
      - started.json
      optional_files:
      - finished.json
    - lens:
        name: buildlog
      required_files:
      - build-log.txt
      optional_files:
      - clone-log.txt
    - lens:
        name: junit
      required_files:
      - artifacts/report.xml

branch-protection:
  orgs:
    bells17-labs:
      protect: true
      exclude:
        - "^revert-" # don't protect revert branches
      repos:
        test-infra:
          restrictions:
            users: []
            teams:
            - stage-bots
